In [1]:
from sqlalchemy import create_engine

In [2]:
username = "postgres"
password = "Odunayo2002"
host = "localhost"
port = "5432"
database = "hngride"

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

In [3]:
import pandas as pd

query = "SELECT * FROM payments LIMIT 5;"
df = pd.read_sql(query, engine)

df

   payment_id  ride_id  amount   method           paid_date
0           1        1   32.26  pay pal 2022-01-27 10:42:00
1           2        2    0.00     cash 2021-07-24 15:28:00
2           3        3    0.00  voucher 2023-07-25 21:32:00
3           4        4   26.73     cash 2021-02-26 03:34:00
4           5        5   55.85     card 2024-08-17 03:43:00

In [10]:
from sqlalchemy import text

create_table = text("""
                    CREATE TABLE employees (
                    employee_id INT PRIMARY KEY, 
                    name VARCHAR(100), 
                    department VARCHAR(50), 
                    salary INT, 
                    years_experience INT, 
                    hire_date DATE
                    );
                    """)

with engine.connect() as conn:
    conn.execute(create_table)
    conn.commit()

In [11]:
insert_data = text("""
INSERT INTO employees VALUES
(1, 'Alice Johnson', 'Sales', 60000, 5, '2019-01-15'),
(2, 'Bob Smith', 'IT', 75000, 7, '2017-03-22'),
(3, 'Charlie Brown', 'HR', 55000, 3, '2021-06-10'),
(4, 'Diana Prince', 'Sales', 65000, 6, '2018-09-05'),
(5, 'Eve Wilson', 'IT', 80000, 10, '2012-11-20');
""")

with engine.connect() as conn:
    conn.execute(insert_data)
    conn.commit()

In [12]:
query = "SELECT * FROM employees;"
df = pd.read_sql(query, engine)

df

   employee_id           name department  salary  years_experience   hire_date
0            1  Alice Johnson      Sales   60000                 5  2019-01-15
1            2      Bob Smith         IT   75000                 7  2017-03-22
2            3  Charlie Brown         HR   55000                 3  2021-06-10
3            4   Diana Prince      Sales   65000                 6  2018-09-05
4            5     Eve Wilson         IT   80000                10  2012-11-20

In [ ]:
# Assignment:
#  Building on yesterday's class, where we created an SQLite3 database, an employee table, and inserted data for analysis, I want you to:

# 1. Create a sales table and insert relevant data.
# 2. Create a department table and insert relevant data.
# 3. Run the output and perform analysis on the data.

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
np.random.seed(42)

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

cursor.execute('''CREATE TABLE sales (
    sale_id INTEGER PRIMARY KEY,
    product_name VARCHAR(100),
    department_id INTEGER,
    quantity INTEGER,
    price DECIMAL(10,2),
    sale_date DATE,
    customer_name VARCHAR(100),
    FOREIGN KEY (department_id) REFERENCES department(department_id)
);''')

cursor.execute('''
CREATE TABLE department (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(100),
    manager_name VARCHAR(100),
    location VARCHAR(100)
);''')

In [3]:
department_data = [
    (1,	"Electronics", "Sarah", "Lagos"),
    (2,	"Clothing", "David", "Abuja"),
    (3,	"Groceries", "Mary", "Port Harcourt"),
    (4,	"vehicles", "James", "Ibadan"),
]

sales_data = [
    (1, "Laptop", 1, 1200, "2025-03-01", "John", 1),
    (2, "Shirt", 3, 25, "2025-03-02", "Mary", 2),
    (3, "Rice", 5, 10, "2025-03-02", "David", 3),
    (4, "Corolla", 1, 10, "2025-03-03", "Micheal", 4),
    (5, "Garri", 5, 10, "2025-03-13", "Kolade", 3),
    (6, "Laptop", 2, 10, "2025-03-06", "Victor", 1),
    (7, "Beans", 3, 10, "2025-03-08", "Treasure", 3),
]

cursor.executemany('INSERT INTO department VALUES (?,?,?,?)', department_data)
cursor.executemany('INSERT INTO sales VALUES (?,?,?,?,?,?,?)', sales_data)

In [4]:
cursor.execute("SELECT * FROM department")

all_department = cursor.fetchall()

for employee in all_department:
    print(employee)

(1, 'Electronics', 'Sarah', 'Lagos')
(2, 'Clothing', 'David', 'Abuja')
(3, 'Groceries', 'Mary', 'Port Harcourt')
(4, 'vehicles', 'James', 'Ibadan')

In [5]:
data=pd.read_sql_query(''' Select  * from sales ''', conn)

df_sales=pd.DataFrame(data)
df_sales

,sale_id,product_name,department_id,quantity,price,sale_date,customer_name
0,1,Laptop,1,1200,2025-03-01,John,1
1,2,Shirt,3,25,2025-03-02,Mary,2
2,3,Rice,5,10,2025-03-02,David,3
3,4,Corolla,1,10,2025-03-03,Micheal,4
4,5,Garri,5,10,2025-03-13,Kolade,3
5,6,Laptop,2,10,2025-03-06,Victor,1
6,7,Beans,3,10,2025-03-08,Treasure,3

In [6]:
data=pd.read_sql_query(''' Select  * from department ''', conn)

df_department=pd.DataFrame(data)
df_department

   department_id department_name manager_name       location
0              1     Electronics        Sarah          Lagos
1              2        Clothing        David          Abuja
2              3       Groceries         Mary  Port Harcourt
3              4        vehicles        James         Ibadan

In [7]:
df=df_department[df_department.department_name=='Electronics']
df

   department_id department_name manager_name location
0              1     Electronics        Sarah    Lagos